export const state = {
  language: null,
  defaults: {},
  configCatalogData: null,
  configCatalog: [],
  activeConfigName: "",
  configLoading: false,
  backend: {
    running: false,
    pid: null,
    message: "Backend stopped.",
  },
  fields: {},
  envRows: [],
  ruleRows: [],
  views: {},
  homeStatusBadge: null,
  homeStatusIndicator: null,
  homeStatusText: null,
  homeStatusMeta: null,
  homeActionButton: null,
  utilityBackButton: null,
  utilityGearButton: null,
  utilityLanguageButton: null,
  homeLogList: null,
  homeLogSourceMeta: null,
  homeActivitySource: "backend",
  homeServicesQuickList: null,
  homeServicesSummary: null,
  logCursor: 0,
  logEntries: [],
  logRefreshing: false,
  persistTimer: null,
  configLoadingNote: null,
  presetListContainer: null,
  configEditorHeader: null,
  editingConfigName: "",
  editingConfigDraft: "",
  configEditorBody: null,
  configTabButtons: [],
  configListTitle: null,
  configListSubtitle: null,
  configNewButton: null,
  configEditorEyebrow: null,
  configEditorSubtitle: null,
  configDeleteButtons: [],
  configDuplicateButtons: [],
  activeConfigTab: "general",
  ruleList: null,
  envList: null,
  activeView: "home",
  refreshing: false,
  appContent: null,
  capturesData: {
    items: [],
    notes: [],
  },
  capturesOrderedEntries: {
    screen: [],
    audio: [],
    notes: [],
  },
  capturesFilter: "screen",
  capturesList: null,
  capturesLoading: false,
  capturesTabButtons: [],
  capturesRefreshTimer: null,
  capturesVisibleOrder: {
    screen: [],
    audio: [],
    notes: [],
  },
  capturesSeenIds: new Set(),
  capturesEntrySnapshot: new Map(),
  capturesRenderedEntries: {
    screen: new Map(),
    audio: new Map(),
    notes: new Map(),
  },
  capturesExpandedItems: new Set(),
  capturesExpandedNotes: new Set(),
  capturesMediaCache: new Map(),
  capturesNoteCache: new Map(),
  capturesModal: null,
  capturesModalHeading: null,
  capturesModalImage: null,
  capturesModalPath: "",
  capturesModalTitle: "",
  capturesModalCloseButton: null,
  capturesModalListenerBound: false,
  servicesList: [],
  servicesSelectedName: null,
  servicesActiveTab: "config",
  servicesLogCursors: {},
  servicesLogEntries: {},
  servicesConfigs: {},
  servicesFields: {},
  servicesStatusButton: null,
  servicesListContainer: null,
  servicesDetailContainer: null,
  servicesLogsPanel: null,
  servicesConfigPanel: null,
  servicesTabButtons: [],
  servicesRefreshTimer: null,
  servicesLogsTimer: null,
  utilityServicesButton: null,
};

export const appRoot = document.getElementById("app");
export const errorText = document.getElementById("error-text");
